module Page.Home exposing (view)

import Html exposing (Html, div, h1, img, p, text)
import Html.Attributes exposing (class, src)


view : Html msg
view =
    div [ class "home-page" ]
        [ img [ src "../assets/images/cv/160_cropPortrait.jpg", class "home-img" ] []
        , h1 [] [ text "Bonjour et bienvenue" ]
        , p [ class "p-home-page" ] [ text "Je m'appelle Pieris RASSAT (framend sur irc et le web)." ]
        , p [ class "p-home-page" ] [ text "Je suis développeur web fullstack." ]
        , p [ class "p-home-page" ] [ text "Autodidacte et éternel étudiant, je suis en cours d'obtention d'un titre RNCP n°32173 «\u{202F}Développeur Web\u{202F}», niveau Bac +2 auprès d'Openclassroom." ]
        , p [ class "p-home-page" ] [ text "En me reconvertissant, j'ai enfin pû allier ma passion pour la programmation à mon besoin de créer." ]
        , p [ class "p-home-page" ] [ text "Je suis curieux et toujours intéressé par l'apprentissage de nouveaux langages et frameworks. " ]
        , p [ class "p-home-page" ] [ text " J'apprécie particulièrement la programmation fonctionnelle, mais j'utilise également l'orienté objet via React, Vue ou TypeScript pour créer des applications dynamiques et attrayantes." ]
        , p [ class "p-home-page" ] [ text "Ma créativité est mon moteur. J'aime trouver des solutions originales et créer des expériences utilisateur uniques." ]
        , p [ class "p-home-page" ] [ text "Je sais démêler les problèmes complexes pour les rendre plus faciles à gérer. Je suis méticuleux et je m'assure toujours de produire des résultats précis et fiables." ]
        , p [ class "p-home-page-training" ] [ text "Laissez moi vous présenter mon parcours de formation\u{202F}:" ]
        , div [ class "milestones-training-wrapper" ]
            [ div [ class "milestnones-training-right" ] [ text "Depuis 2018" ]
            , div [ class "milestnones-training" ]
                [ text "Développement HTML/CSS JavaScript et PHP (Laravel), administration Debian/Nginx/Git" ]
            , div [ class "milestnones-training-right" ]
                [ div [] [ text "Projet Openclassroom\u{202F}:" ]
                , div [] [ text "Créez la page d'accueil d'une agence de voyage avec HTML & CSS" ]
                ]
            , div [ class "milestnones-training" ] [ text "Décembre 2022" ]
            , div [ class "milestnones-training-right" ] [ text "Janvier 2023" ]
            , div [ class "milestnones-training" ]
                [ div [] [ text "Projet Openclassroom\u{202F}:" ]
                , div [] [ text "Planifiez le développement du site de votre client" ]
                ]
            , div [ class "milestnones-training-right" ]
                [ div [] [ text "Projet Openclassroom\u{202F}:" ]
                , div [] [ text "Débuggez et optimisez un site de photographe" ]
                ]
            , div [ class "milestnones-training" ] [ text "Février 2023" ]
            , div [ class "milestnones-training-right" ] [ text "Mars 2023" ]
            , div [ class "milestnones-training" ]
                [ div [] [ text "Projet Openclassroom\u{202F}:" ]
                , div [] [ text "Créez une application React" ]
                ]
            , div [ class "milestnones-training-right" ]
                [ div [] [ text "Projet Openclassroom\u{202F}:" ]
                , div [] [ text "Développez le back-end d'un site de notation de livres" ]
                ]
            , div [ class "milestnones-training" ] [ text "Avril 2023" ]
            , div [ class "milestnones-training-right" ] [ text "Mai 2023" ]
            , div [ class "milestnones-training" ]
                [ div [] [ text "Projet Openclassroom\u{202F}:" ]
                , div [] [ text "Créez et publiez votre portfolio de développeur" ]
                ]
            , div [ class "milestnones-training-right" ] [ text "Développement du frontend de ./play.it, un générateur de paquets pour jeux sans DRM" ]
            , div [ class "milestnones-training" ] [ text "Juin 2023" ]
            , div [ class "milestnones-training-right" ] [ text "Juin 2023" ]
            , div [ class "milestnones-training" ] [ text "Réécriture de l'API de ./play.it en PHP 8 via Lumen" ]
            , div [ class "milestnones-training-right" ] [ text "Depuis juin 2023" ]
            , div [ class "milestnones-training" ] [ text "Développement de frontends en elm et de backend en PHP ou Express.js" ]
            , div [ class "milestnones-training-vert-line" ] [ text "" ]
            , div [ class "milestnones-training-dot1" ] [ text "" ]
            , div [ class "milestnones-training-dot2" ] [ text "" ]
            , div [ class "milestnones-training-dot3" ] [ text "" ]
            , div [ class "milestnones-training-dot4" ] [ text "" ]
            , div [ class "milestnones-training-dot5" ] [ text "" ]
            , div [ class "milestnones-training-dot6" ] [ text "" ]
            , div [ class "milestnones-training-dot7" ] [ text "" ]
            , div [ class "milestnones-training-dot8" ] [ text "" ]
            , div [ class "milestnones-training-dot9" ] [ text "" ]
            , div [ class "milestnones-training-dot10" ] [ text "" ]
            ]
        ]
