module Page.Resume exposing (view)

import Html exposing (..)
import Html.Attributes exposing (..)


view : Html msg
view =
    div [ id "main-wrapper" ]
        [ div []
            [ div [ class "resume-header" ]
                [ h1 [ class "main-title" ] [ text "Développement web" ]
                , h2 [ class "main-subtitle" ] [ text "Développeur fullstack" ]
                ]
            , section [ class "training" ]
                [ h2 [] [ text "FORMATION" ]
                , ul []
                    [ li []
                        [ div [ class "li-wrapper" ]
                            [ div [ class "li-obtention-year" ] [ text "2023\u{202F}:" ]
                            , div [ class "li-details-wrapper" ]
                                [ div [ class "li-title" ] [ text "TP développeur web (6)" ]
                                , div [ class "li-location" ] [ text "Openclassrooms.com - Paris (75)" ]
                                ]
                            ]
                        ]
                    , li []
                        [ div [ class "li-wrapper" ]
                            [ div [ class "li-obtention-year" ] [ text "2017\u{202F}:" ]
                            , div [ class "li-details-wrapper" ]
                                [ div [ class "li-title" ] [ text "BPREA Maraîchage - Arboriculture (4)" ]
                                , div [ class "li-location" ] [ text "CFPPA Olivier de Serre - Mirabel (07)" ]
                                ]
                            ]
                        ]
                    , li []
                        [ div [ class "li-wrapper" ]
                            [ div [ class "li-obtention-year" ] [ text "2015\u{202F}:" ]
                            , div [ class "li-details-wrapper" ]
                                [ div [ class "li-title" ] [ text "DRJSCS Examen de niveau (4)" ]
                                , div [ class "li-location" ] [ text "DDCS - Montpellier (34)" ]
                                ]
                            ]
                        ]
                    , li []
                        [ div [ class "li-wrapper" ]
                            [ div [ class "li-obtention-year" ] [ text "2014\u{202F}:" ]
                            , div [ class "li-details-wrapper" ]
                                [ div [ class "li-title" ] [ text "TP SAP-AVE (3)" ]
                                , div [ class "li-location" ] [ text "IRFA sud - Perpignan (66)" ]
                                ]
                            ]
                        ]
                    , li []
                        [ div [ class "li-wrapper" ]
                            [ div [ class "li-obtention-year" ] [ text "2003\u{202F}:" ]
                            , div [ class "li-details-wrapper" ]
                                [ div [ class "li-title" ] [ text "CAP Photographie (3)" ]
                                , div [ class "li-location" ] [ text "Lycée pro Ste Marie - St-Etienne (42)" ]
                                ]
                            ]
                        ]
                    ]
                ]
            , section [ class "experience" ]
                [ h2 [] [ text "EXPÉRIENCES" ]
                , ul []
                    [ li []
                        [ div [ class "li-wrapper-xp" ]
                            [ div [ class "li-obtention-year-wrapper" ]
                                [ div [ class "li-obtention-year" ] [ text "2022\u{00A0}-\u{00A0}2023\u{202F}:" ]
                                , div [ class "li-title" ] [ text "Développement web JavaScript full stack" ]
                                ]
                            , div [ class "li-details" ]
                                [ div [ class "li-xp-details" ] [ text "Développement : JavaScript – React.js – Express.js – HTML/CSS. Gestion de projet agile. Optimisation jQuery/bootstrap. Debug." ]
                                ]
                            ]
                        ]
                    , li []
                        [ div [ class "li-wrapper-xp" ]
                            [ div [ class "li-obtention-year-wrapper" ]
                                [ div [ class "li-obtention-year" ] [ text "2018\u{00A0}-\u{00A0}2022\u{202F}:" ]
                                , div [ class "li-title" ] [ text "Freelance développement web" ]
                                ]
                            , div [ class "li-details" ]
                                [ div [ class "li-xp-details" ] [ text "Développement PHP-Laravel-Prestashop – JavaScript – HTML/CSS – Installation, maintenance et administration serveurs Linux (Debian-Nginx)." ]
                                ]
                            ]
                        ]
                    , li []
                        [ div [ class "li-wrapper-xp" ]
                            [ div [ class "li-obtention-year-wrapper" ]
                                [ div [ class "li-obtention-year" ] [ text "2015\u{202F}:" ]
                                , div [ class "li-title" ] [ text "Moniteur éducateur en CHRS" ]
                                ]
                            , div [ class "li-details" ]
                                [ div [ class "li-xp-details" ] [ text "Accueil et accompagnement, centre d'hébergement du 115." ]
                                ]
                            ]
                        ]
                    , li []
                        [ div [ class "li-wrapper-xp" ]
                            [ div [ class "li-obtention-year-wrapper" ]
                                [ div [ class "li-obtention-year" ] [ text "2006\u{00A0}-\u{00A0}2018\u{202F}:" ]
                                , div [ class "li-title" ] [ text "Charpentier" ]
                                ]
                            , div [ class "li-details" ]
                                [ div [ class "li-xp-details" ] [ text "Charpente bois traditionnelle, menuiserie, couverture." ]
                                ]
                            ]
                        ]
                    , li []
                        [ div [ class "li-wrapper-xp" ]
                            [ div [ class "li-obtention-year-wrapper" ]
                                [ div [ class "li-obtention-year" ] [ text "2004\u{00A0}-\u{00A0}2006\u{202F}:" ]
                                , div [ class "li-title" ] [ text "Photographe" ]
                                ]
                            , div [ class "li-details" ]
                                [ div [ class "li-xp-details" ] [ text "Photofilmeur, photographies scolaires, mariages, laborantin." ]
                                ]
                            ]
                        ]
                    ]
                ]
            , section [ class "soft-skills" ]
                [ h2 [] [ text "COMPÉTENCES HUMAINES" ]
                , div [ class "soft-skills-ul-wrapper" ]
                    [ ul []
                        [ li [] [ text "Créativité" ]
                        , li [] [ text "Capacités analytiques" ]
                        , li [] [ text "Relations publiques" ]
                        , li [] [ text "Gestion des délais" ]
                        ]
                    , ul []
                        [ li [] [ text "Travail en équipe" ]
                        , li [] [ text "Vulgarisation technique" ]
                        , li [] [ text "Travail distanciel" ]
                        , li [] [ text "Autonomie" ]
                        ]
                    ]
                ]
            , section [ class "skills" ]
                [ h2 [] [ text "COMPÉTENCES TECHNIQUES" ]
                , div [ class "skills-ul-wrapper" ]
                    [ ul []
                        [ li [] [ text "PHP - Laravel - Lumen" ]
                        , li [] [ text "Elm" ]
                        , li [] [ text "Vue.js" ]
                        , li [] [ text "SQL - MariaDB" ]
                        , li [] [ text "Debian - Qemu/KVM" ]
                        ]
                    , ul []
                        [ li [] [ text "JavaScript - TypeScript" ]
                        , li [] [ text "HTML5/CSS3" ]
                        , li [] [ text "React.js" ]
                        , li [] [ text "NoSQL - MongoDB" ]
                        , li [] [ text "Git - SSH" ]
                        ]
                    ]
                ]
            , div [ class "resume-download-container" ]
                [ div [ class "resume-download-wrapper" ] [ text "" ]
                , a [ href "../../assets/dl/devCv.pdf", download "Pieris_RASSAT_dev-resume.pdf" ] [ text "CV.pdf" ]
                ]
            ]
        , aside [ class "main-aside" ]
            [ section [ class "id" ]
                [ h2 [ class "main-aside-title p-center" ] [ text "RASSAT Pieris" ]
                , p [ class "postal-address p-center" ] [ text "14 bvd Joffre" ]
                , p [ class "postal-address p-center" ] [ text "66400 CÉRET" ]
                , p [ class "tel p-center" ] [ text "+3349692920" ]
                , a [ href "mailto:pieris@tuta.io" ] [ text "pieris@tuta.io" ]
                ]
            , section [ class "main-image" ]
                [ div [ class "main-image-wrapper" ] []
                ]
            , section [ class "additional" ]
                [ p [ class "website p-center" ] [ a [ href "https://www.framend.com" ] [ text "framend.com" ] ]
                , p [ class "cv-github" ] [ a [ href "https://github.com/pierisRassat" ] [ text "\u{EB00} github" ] ]
                , p [ class "cv-gitlab" ] [ a [ href "https://gitlab.com/web-apps3574524" ] [ text "\u{F0BA0} gitlab" ] ]
                , div [ class "lang-wrapper" ]
                    [ div [ class "lang-1-lang" ]
                        [ p [ class "lang-1" ] [ text "Anglais " ]
                        , p [ class "lang-2" ] [ text "Espagnol" ]
                        ]
                    , div [ class "lang-2-lang" ]
                        [ p [ class "lang-1" ] [ text "\u{F192}\u{F192}\u{F192}\u{F192}\u{F10C} " ]
                        , p [ class "lang-2" ] [ text "\u{F192}\u{F192}\u{F192}\u{F10C}\u{F10C}" ]
                        ]
                    ]
                ]
            ]
        ]
